---
title: "**Syllabus(课程计划)** "
subtitle: "Intro 'Metrics, Spring 2024"
# author: "Instructor:曲兆鹏;TA:王紫澍"
# institute: "南京大学"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{=html}
<style type="text/css">
  body{
  font-size: 13pt;
}
</style>
```
### Course Description

This course introduces students to modern causal inference methods for analyzing data in economics and other social sciences. The goal is to help you develop a solid theoretical background in introductory level econometrics, the ability to implement modern econometric methods, and the critical thinking about empirical studies in economics and other social sciences. Specifically, we will learn **seven** modern econometric research design techniques that aim to estimate causal effects credibly and make predictions scientifically on economic and social relationships:

-   *Randomized Controlled Trial(RCT)*

-   *Regression(OLS)*

-   *Instrumental Variables(IV)*

-   *Regression Discontinuity Designs(RDD)*

-   *Panel Data and Differences-in-Differences(DID)*

-   *Introduction to Times Series(TS)*

-   *Machine Learning and Forecasting(ML)*

At the end, students will use at least one of them above to finish an empirical research proposal.

### Evaluation

-   Participation（$10\%$）

-   Homework ($10\%\times2=20\%$)

-   Final exam ($40\%$)

-   Group project ($30\%$)

### Textbooks

#### Econometrics

-   James H. Stock and Mark W. Watson, *Introduction to Econometrics*, 3rd Edition, Addison-Wesley, 2012.

-   Jeffrey M. Wooldridge, *Introductory Econometrics: A Modern Approach*, 5th Edition, South-Western College, 2013.

-   Joshua Angrist and Jorn-Steffen Pischke, *Mastering' Metrics: The Path from Cause to Effect*, Princeton press, 2015.

• Joshua Angrist and Jorn-Steffen Pischke, *Mostly Harmless Econometrics: An Empiricist's Companion*, Princeton press, 2008.

-   Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani, *An Introduction to Statistical Learning: with Applications in R*, Springer, 2013.

#### Computing Softwares： Stata and R

-   任意一本关于Stata或R的中文书

#### Additional Readings

-   Steven D. Levitt and Stephen J. Dubner, Freakonomics: A Rogue Economist Explores the Hidden Side of Everything, 2005. (中译本《魔鬼经济学》 斯蒂夫\cdot列维特和斯蒂芬\\cdot都伯纳著，广东经济出版社，2006年1月。)

-   Steven D. Levitt and Stephen J. Dubner, SuperFreakonomics: Global Cooling, Patriotic Prostitutes, and Why Suicide Bombers Should Buy Life Insurance, 2009.（中译本，《超爆魔鬼经济学》，斯蒂夫\cdot列维特和斯蒂芬\\cdot都伯纳著，中信出版社，2010年1月。）

-   Ian Ayres, Super Crunchers: Why Thinking-By-Numbers is the New Way To Be Smart, 2007. (中译本《超级数字天才》，伊恩\cdot艾瑞斯著，中国青年出版社，2008年1月。)

-   Raymond Fisman and Edward Miguel, Economic Gangster：Corruption, Violence and the Poverty of Nations, 2008. (中译本《经济黑帮：腐败、暴力的黑帮经济学》，中信出版社，2010年8月)

-   Abhijit V. Banerjee & Esther Duflo, Poor Economics A Radical Rethinking of the Way to Fight Global Poverty, 2011.(中译本:《贫穷的本质：我们为什么摆脱不了贫穷》，中信出版社。）

-   Angus Deaton, The Great Escape:Health,Wealth,and the Origins of Inequality,2015.(中译本: 《逃离不平等: 健康、财富及不平等的起源》，中信出版社。）

-   涂子沛，《大数据：正在到来的数据革命，以及它如何改变政府、商业与我们的生活》，广西师范大学出版社，2012年7月。

### Outline

(Preliminary, to be adjusted possibly)

1.  **Introduction**

-   What the course is about? What is the benefit if we learn it? How to learn it?

-   Probability and Statistics Review

    -   Stock and Watson (2012): Chapter 2-3.

    -   Wooldridge (2013): Appendix A, B & C.

2.  **Causal Inference in Social Science and Randomized Experiment(I)**

-   Stock and Watson (2012): Chapter 1 & 13

-   Angrist and Pischke (2014): Chapter 1

-   Angrist and Pischke (2008): Chapter 1-2

-   Probability and Statistics Review

    -   Stock and Watson (2012): Chapter 2-3.
    -   Wooldridge (2013): Appendix A, B & C.

3.  **Causal Inference in Social Science and Randomized Experiment(II)**

-   Stock and Watson (2012): Chapter 1 & 13

-   Angrist and Pischke (2014): Chapter 1

-   Angrist and Pischke (2008): Chapter 1-2

-   Probability and Statistics Review

    -   Stock and Watson (2012): Chapter 2-3.
    -   Wooldridge (2013): Appendix A, B & C.

4.  **Regression (I): Simple OLS-Estimation**

-   Stock and Watson (2012): Chapter 4-5, 17

-   Wooldridge (2013): Chapter 2

-   Angrist and Pischke (2014):Chapter 2

-   Angrist and Pischke (2008): Chapter 3

5.  **Regression (II)- Multiple OLS-Hypothesis Test**

-   Stock and Watson (2012): Chapter 6-7

-   Wooldridge (2013): Chapter 3,

-   Angrist and Pischke (2008): Chapter 3

-   Angrist and Pischke (2014): Chapter 2

6.  **Regression Review (III): Multiple OLS-Estimation and Hypothesis Test**

-   Stock and Watson (2012): Chapter 6-7

-   Wooldridge (2013): Chapter 4-5

7.  **Regression Review (IV): Nonlinear Regression Functions**

-   Stock and Watson (2012): Chapter 8-9

-   Wooldridge (2013): Chapter 6-8

8.  **Regression Review (V): Binary Dependent Variables**

-   Stock and Watson (2012): Chapter 11

-   Wooldridge (2013): Chapter 9 & 17

9.  **Instrumental Variables (I)**

-   Stock andWatson (2012): Chapter 12

-   Wooldridge (2013): Chapter 15

-   Angrist and Pischke (2014): Chapter 3

-   Angrist and Pischke (2008): Chapter 4

10. **Instrumental Variables (II)**

-   Stock and Watson (2012): Chapter 12

-   Wooldridge (2013): Chapter 15

-   Angrist and Pischke (2014): Chapter 3

-   Angrist and Pischke (2008): Chapter 4

11. **Regression Discontinuity (I)**

-   Angrist and Pischke (2008): Chapter 4

-   Angrist and Pischke (2014): Chapter 4

-   Guido W. Imbens and Thomas Lemieux (2007), “Regression discontinuity designs: A guide to practice”, Journal of Econometrics, 142(2), pp.615-635.

12. **Regression Discontinuity (II)**

-   Angrist and Pischke (2008): Chapter 4

-   Angrist and Pischke (2014): Chapter 4

-   Guido W. Imbens and Thomas Lemieux (2007), “Regression discontinuity designs: A guide to practice”, Journal of Econometrics, 142(2), pp.615-635.

13. **Fixed Effect and Difference in Differences (I)**

-   Angrist and Pischke (2014): Chapter 5

-   Stock and Watson (2012): Chapter 10

-   Wooldridge (2013): Chapter 13

14. **Fixed Effect and Difference in Differences (II)**

-   Angrist and Pischke (2014): Chapter 5

-   Stock and Watson (2012): Chapter 10

-   Wooldridge (2013): Chapter 13

15. **Introduction to Times Series (I)**

-   Stock and Watson (2012): Chapter 14

-   James et al (2013): Chapter 1

16. **Introduction to Times Series (II)**

-   Stock and Watson (2012): Chapter 15

-   James et al (2013): Chapter 2

17. **Final Review**
